# Generated by Django 2.2.14 on 2022-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220415_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('ADI', 'ADIDAS'), ('NIK', 'NIKE'), ('UAM', 'UNDER ARMOUR'), ('VAN', 'VANS')], default='ADIDAS', max_length=3),
        ),
    ]
